options:
  logging: CLOUD_LOGGING_ONLY


steps:

#######################################################
# RESTORE CACHE FROM CLOUD STORAGE
#######################################################

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

  entrypoint: bash

  args:

    - -c

    - |

      echo "Checking Cloud Storage cache..."

      mkdir -p /workspace/cache


      gsutil cp gs://$_CACHE_BUCKET/ubuntu-cloud.img /workspace/cache/ || true


      if [ -f /workspace/cache/ubuntu-cloud.img ]; then

        echo "Cache found. Restoring artifact..."

        cp /workspace/cache/ubuntu-cloud.img .

      else

        echo "No cache available."

      fi



#######################################################
# DOWNLOAD DEPENDENCY IF CACHE DOES NOT EXIST
#######################################################

- name: 'ubuntu:24.04'

  entrypoint: bash

  args:

    - -c

    - |

      if [ -f ubuntu-cloud.img ]; then

        echo "Using cached dependency."

      else

        echo "Downloading large dependency..."

        apt-get update

        apt-get install -y wget


        wget -O ubuntu-cloud.img \
        https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img


      fi



#######################################################
# UPDATE CACHE
#######################################################

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'

  entrypoint: bash

  args:

    - -c

    - |

      echo "Uploading artifact to Cloud Storage cache..."

      gsutil cp ubuntu-cloud.img gs://$_CACHE_BUCKET/ubuntu-cloud.img



#######################################################
# BUILD CONTAINER IMAGE
#######################################################

- name: 'gcr.io/cloud-builders/docker'

  args:

    - build

    - -t

    - europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest

    - .



#######################################################
# PUSH IMAGE
#######################################################

- name: 'gcr.io/cloud-builders/docker'

  args:

    - push

    - europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest



#######################################################
# OUTPUT IMAGE
#######################################################

images:

- europe-west1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_IMAGE:latest
